[package]
name = "csv2parquet"
version = "0.8.1"
authors = ["Dominik Moritz <domoritz@cmu.edu>"]
license = "MIT/Apache-2.0"
edition = "2018"
repository = "https://github.com/domoritz/arrow-tools"
description = "Convert CSV files to Parquet"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parquet = "34.0.0"
arrow = "34.0.0"
arrow-schema = { version = "34.0.0", features = ["serde"] }
serde_json = "1.0.91"
clap = { version = "4.1.8", features = ["derive"] }
